export const data = [
  {
    id: 4001126,
    product: "Karo Hass",
    type: "Nacional",
    size: "Mediano",
    unit: "kg",
    price: 1980,
  },
  {
    id: 4001127,
    product: "Neland Hass",
    type: "Nacional",
    size: "Grande",
    unit: "kg",
    price: 2210,
  },
  {
    id: 4001128,
    product: "Aguacate Hass",
    type: "Importado",
    size: "Pequeño",
    unit: "kg",
    price: 1700,
  },
  {
    id: 4001129,
    product: "Aguacate Hass",
    type: "Nacional",
    size: "Super Extra",
    unit: "kg",
    price: 2890,
  },
  {
    id: 4001130,
    product: "Aguacate Hass",
    type: "Importado",
    size: "Supremo",
    unit: "kg",
    price: 3500,
  },
];
